# Generated by Django 2.0.5 on 2018-12-04 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('avg_stars', models.CharField(max_length=3)),
                ('categories', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('stars', models.CharField(max_length=3)),
                ('prediction', models.CharField(max_length=3)),
                ('review_id', models.CharField(default='', editable=False, max_length=30)),
                ('business_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Business')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Users')),
            ],
        ),
    ]
